version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
  account-api:
    build:
      context: .
      dockerfile: ./service.account-api/Dockerfile
    env_file: .env
    environment: 
      DB_HOST: database
    ports:
      - "9090:9090"
    depends_on:
      - database
    links:
      - database
  image-storage:
    build:
      context: .
      dockerfile: ./server.image-storage/Dockerfile
    env_file: .env
    ports:
      - "9090:9091"

volumes:
  data: