basePath: /
consumes:
- application/json
definitions:
  Account:
    description: Account is the database struct
    properties:
      age:
        description: the age of this account
        format: uint8
        type: integer
        x-go-name: Age
      birthday:
        description: the birthday of this account
        format: date-time
        type: string
        x-go-name: Birthday
      email:
        description: the email of this account
        type: string
        x-go-name: Email
      id:
        description: the id for this account
        format: uint64
        minimum: 1
        type: integer
        x-go-name: ID
      name:
        description: the name of this account
        type: string
        x-go-name: Name
      username:
        description: the username of this account
        type: string
        x-go-name: Username
    required:
    - id
    - name
    - email
    - username
    - birthday
    type: object
    x-go-package: github.com/florianwoelki/insta-clone/internal
info:
  description: Documentation for Account API
  title: of Account API
  version: 1.0.0
paths:
  /account/{id}:
    get:
      description: Returns a single account by a id
      operationId: listAccount
      responses:
        "200":
          $ref: '#/responses/accountResponse'
      tags:
      - accounts
produces:
- application/json
responses:
  accountResponse:
    description: A single account response
    headers:
      id:
        description: |-
          The id of the account that will be returned
          in: path
          required: true
        format: uint64
        type: integer
    schema:
      items:
        $ref: '#/definitions/Account'
      type: array
schemes:
- http
swagger: "2.0"
